name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Thư viện cho đa ngôn ngữ
  flutter_localizations:
    sdk: flutter
  # SỬA LỖI: Nâng cấp intl để khớp với yêu cầu của flutter_localizations
  intl: ^0.20.2

  # --- State Management ---
  # CẬP NHẬT: Chỉ giữ lại flutter_riverpod và nâng cấp lên phiên bản mới nhất
  flutter_riverpod: ^2.5.1

  # --- UI & UX ---
  image_picker: ^1.1.2
  fl_chart: ^0.68.0
  lottie: ^3.1.2
  cupertino_icons: ^1.0.8

  # --- Data & Storage ---
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code generators
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  # CẬP NHẬT: Nâng cấp lints
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/images/